on:
  push:
    branches: [main]
name: 🚀 Deploy website on push - Lead Serasa - Front-End
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v2

      - name: Use Node.js 14
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: 🔨 Build Project
        run: |
          npm install
          npm run build

      - name: 🔨 Listando Arquivos
        run: |
          ls

      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.SERVE_LEAD_SERASA_FRONT }}
          username: ${{ secrets.USERNAME_LEAD_SERASA_FRONT }}
          password: ${{ secrets.PASSWORD_LEAD_SERASA_FRONT }}
          dangerous-clean-slate: true
          local-dir: './dist/lead-clear-serasa-name/'
          server-dir: public_html/
          port: 21

